### PR TITLE
Support OpenStack Swift as a backend

### PR DESCRIPTION
**Pull request by yoyama**
I implemented OpenStack Swift backend.
I am glad if it is useful and acceptable.

Best regards,
  You Yamagata

---

To run test_bakthat_swift.py, a Swift cluster is required.
(It may be better to prepare for mock of swiftclient)

Swift is multi server system, but you can build a clust
with a server by SAIO (Swift All in One).
http://docs.openstack.org/developer/swift/development_saio.html

### CODE REVIEW

**Comment by tsileo** [comment]
Awesome ! Thanks, it's perfect, from tests to documentation.
I think it's a good occasion for me to try swift, I'll try to setup a cluster.

Let me know if you have some ideas to improve bakthat !

**Comment by tsileo** [comment]
Also, I added you to bakthat collaborators, if you make some changes, you can either send a pull request or directly push your commits.

**Comment by yoyama** [comment]
I appreciate merging quickly and adding me to bakthat collaborator.
I will continue to contribute to bakthat !

**Comment by tsileo** [comment]
Just to let you know that I released your changes in bakthat 0.5.0: http://thomassileo.com/blog/2013/04/24/bakthat-0-dot-5-0-released-with-openstack-swift-support-and-bakmanager-integration/

Thanks again !

**Pull request merged**
